//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousingStock
    {
        public int HousingStockID { get; set; }
        public int StreetID { get; set; }
        public int HouseNumberID { get; set; }
        public int CityID { get; set; }
        public Nullable<System.DateTime> BeginningManagement { get; set; }
        public Nullable<int> Floors { get; set; }
        public Nullable<int> Flats { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<double> Square { get; set; }
    
        public virtual City City { get; set; }
        public virtual HouseNumber HouseNumber { get; set; }
        public virtual Street Street { get; set; }
    }
}
