//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentID { get; set; }
        public int OwnerID { get; set; }
        public int CityID { get; set; }
        public int StreetID { get; set; }
        public int HouseNumberID { get; set; }
        public Nullable<int> Flat { get; set; }
        public string Period { get; set; }
        public Nullable<double> Accrual { get; set; }
        public Nullable<double> Paid { get; set; }
    
        public virtual City City { get; set; }
        public virtual HouseNumber HouseNumber { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual Street Street { get; set; }
    }
}
